name: Score robot

on:
  repository_dispatch:
    types: [uj_score_erkezett]

permissions:
  contents: write

jobs:
  mentes:
    runs-on: ubuntu-latest
    steps:
      - name: Repó letöltése
        uses: actions/checkout@v4

      - name: Új sor hozzáírása a dokumentumhoz
        run: |
          echo "${{ github.event.client_payload.jatekos }}: ${{ github.event.client_payload.valasz }}" >> scores.txt

      - name: Változtatások mentése a GitHubra
        run: |
          git config --global user.name "Cukika Robot"
          git config --global user.email "robot@cukika.local"
          git add scores.txt
          git commit -m "Új pontszám hozzáadva: ${{ github.event.client_payload.jatekos }}"
          git push
